---
rules:

- name: close_issues_older_than_5_minutes
  rule: close_outdated_issues
  options:
    # ISO 8601 duration
    older_than: PT5M
    # Optional, apply label when closing
    apply_label: inactive
    # Optional, leave a comment when closing
    add_comment: |
      Sorry, closing the issue as its older than 5 minutes

- name: close_outdated_prs_older_than_20_days
  rule: close_outdated_pr
  options: 
    # ISO 8601 duration
    older_than: P20D
    # Optional, apply label when closing
    apply_label: inactive
    # Optional, leave a comment when closing
    add_comment: |
      Sorry, closing the pr as its older than 20 days

- name: pr_matches_format
  rule: pr_format
  options:
    # Array of case-insensitive regular expressions
    # TODO:
    #   Decide on multi-line flag, escaping special characters, full vs partial match and other specific regex behaviors
    #   Behavior with multiple commits on a PR (squash commits, merge commits, etc)
    #   Matching commit bodies vs PR title vs PR body
    match_title:
      - "^#\\d+"
    # match_commit: ...
    # match_body: ...
    apply_label: invalid
    add_comment: |
      Sorry, PRs must follow conventions:
      1. Title must start with ticket number - #123 ...

- name: pr_size_xs
  # For now we decided to create separare rule for each label that we want to apply, e.g.: if file_based.count is less 
  # than the actual pr size we do nothing. We could enhance this rule in the future to apply a tag according to ranges, e.g:
  # count between 5 .. 10 apply S, count between 10 .. 15 apply M, ...
  rule: pr_size_check
  options:
    strategy: 
      # strategies should be mutually exclusive to avoid conflicts, e.g.: too many files with 1 line change or viceversa.
      #line_based:
        ## counts are also mutually exclusive.
        #count_per_file: 5
        #count_in_total: 20
      file_based:
        count: 1
    apply_label: xs  # For now we don't support array of labels
    #add_comment: (optional, e.g.: warning when PR is too big)
