---
rules:

- name: close_issues_older_than_5_minutes
  rule: close_outdated_issues
  options:
    # ISO 8601 duration
    older_than: PT5M
    # Optional, apply label when closing
    apply_label: inactive
    # Optional, leave a comment when closing
    add_comment: |
      Sorry, closing the issue as its older than 5 minutes
